name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: chabad360/hugo-actions@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: "public"
          container_name: "$web"
          connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
          sync: true
